language: node_js
node_js:
- 13
env:
  matrix:
  - MONGODB_DATABASE=genealogyDb MONGODB=mongodb://localhost:27017/
  deploy: 
  provider: releases
  api_key: 
    secure: l9qQKXhZAbZM4k5nVyoTUorvao2NVY5vBFGG8nvoWCAvWIc2iiK8383YjWh/i+HOye+xAGa8gN3u28EXseQ6VFV06VqEBFnniajawOmPTQLEaanrDdv9EGQqY9nYJw2pJAFAWXpOAdT4IsFeknl0Yluu/fD7+lV7KUsshGI0tTXmN++qYiwAEldCkqayhMyDYA+UyVAKxriuIrp1xAV9bajO/uT/IGh99zIGNst3Agds0vA2pI8sl8w3PsF0V7/Z7QmKpihUEQUH+GA5pPH8/KwF/DD8FogENxrv3RIPaUbZyujZIL3+De/Q7i49d2mcLsa7BIKbfSfada4+r0YGEMSNIMkTqPP7QOf+NJsG9sOrjkzDoUv5xrSrQEVA7qgCcDEoxzz/qUnwSlg3JPRQpIFUB3E5QmAFA+Udd51cmyCmnWB9/dvMr9pRW1HsEtUPwbxLXTlau9asRkGbIB7Chx/55S00dJ6KBO0adqUdZLMRTt6anG1R2Anpo0zQC2Wm3rXrRvNuKkqH/BdY9Y7nFSw9nODo6wbWJqVu4zbNpTpQcKa+sOBfoiDhIiWqFj5/3P9S+QfQqFGh529xXuT5hZmNf53N9HDOZYA439HBpDNvAaBo2LIiy8uZaXHaa/nEhUhdlcC+MzDMOeYj6sATx4BgUs1KXlxBNfEwB/VvCpk=

  file: dist/**
  cleanup: false
  draft: true
  on:
    branch: prod
  script: npm test
after_success: npm run coverage
